!############################# Change Log ##################################
! 5.0.0
!
!###########################################################################
!  Copyright (C)  1990, 1995, 1999, 2000, 2003 - All Rights Reserved
!  Regional Atmospheric Modeling System - RAMS
!###########################################################################

module ModSingleGridNamelist

  use ModNamelistFile, only: &
       NamelistFile

  use grid_dims, only: &
       nzpmax, &
       maxsteb, &
       maxubtp, &
       maxlite, &
       nzgmax
  
  implicit none

  include "files.h"
  integer, parameter :: maxodagrids=10
  integer, parameter :: maxcugrids=10
  integer, parameter :: ncat_dummy=8
  integer, parameter :: maxsndg=200
  integer, parameter :: maxisn=100
  integer, parameter :: maxagrds=10
  integer, parameter :: nsrc=4

  private
  public :: SingleGridNamelist
  public :: CreateSingleGridNamelist
  public :: DestroySingleGridNamelist


  type SingleGridNamelist
     integer :: advmnt
     integer :: aer_assim
     real :: aer_timestep
     integer :: aerosol
     character(len=f_name_length) :: afilout
     real :: akmin
     real :: albedo
     character(len=10) :: anl2gra
     real :: aparm
     logical :: applyDigitalFilter
     integer :: applyIAU
     logical :: applyMeteogram
     real :: aroad(maxubtp)
     real :: aroof(maxubtp)
     character(len=20) :: ascii_data
     real :: avgtim
     real :: awall(maxubtp)
     real :: bld(maxubtp)
     real :: bld_height(maxubtp)
     real :: bld_hl_ratio(maxubtp)
     integer :: catt
     integer :: ccGradsWrite
     integer :: ccatt
     real :: centlat
     real :: centlon
     integer :: chem_assim
     real :: chem_timestep
     character(len=f_name_length) :: chemdata_in
     integer :: chemistry
     integer :: chemistry_aq
     character(len=2) :: closure_type
     real :: cnparm
     character(len=f_name_length) :: coltabfn
     character(len=f_name_length) :: cond_hfile
     real :: confrq
     real :: cparm
     real :: cphas
     character(len=f_name_length) :: csvFile
     real :: csx
     real :: csz
     character(len=128) :: cu_prefix
     real :: cu_tel
     real :: cu_til
     real :: d_road(maxsteb)
     real :: d_roof(maxsteb)
     real :: d_wall(maxsteb)
     integer :: damModule
     character(len=256) :: damOutPrefix
     real :: daylight
     character(len=32) :: def_proc_src
     integer :: define_proc
     real :: deltax
     real :: deltay
     real :: deltaz
     real :: digitalFilterTimeWindow
     real :: distim
     integer :: diur_cycle(nsrc)
     real :: dlimit(5)
     character(len=f_name_length) :: domain_fname
     real :: dparm
     real :: drtcon
     real :: dthcon
     real :: dtlong
     integer :: dyncore_flag
     real :: dzmax
     real :: dzrat
     real :: efsat
     real :: efsun
     real :: eindco
     real :: eindno
     real :: eindno2
     real :: eindpm
     real :: eindso2
     real :: eindvoc
     real :: epsil
     real :: eroad(maxubtp)
     real :: eroof(maxubtp)
     integer :: evaluate
     character(len=256) :: evaluatePrefix
     real :: eveico
     real :: eveino
     real :: eveino2
     real :: eveipm
     real :: eveiso2
     real :: eveivoc
     real :: ewall(maxubtp)
     character(len=64) :: expnme
     character(len=f_name_length) :: fileName
     character(len=f_name_length) :: fileNameIAU
     real :: final_latitude
     real :: final_longitude
     character(len=256) :: firemapfn
     integer :: fixLevels
     real :: frqPrecip
     real :: frqanl
     real :: frqboth
     real :: frqhis
     real :: frqlite
     real :: frqmean
     real :: frqoda
     real :: frqprt
     character(len=f_name_length) :: fusfiles
     integer :: g3d_smoothh
     integer :: g3d_smoothv
     integer :: g3d_spread
     character(len=32) :: geo_varname
     integer :: ghostzonelength
     real :: gnparm
     real :: gnu(ncat_dummy)
     real :: gobrad
     real :: gobsep
     real :: gparm
     character(len=f_name_length) :: gprefix
     real :: gridu
     real :: gridv
     real :: gridwt(maxagrds)
     character(len=8) :: guess1st
     real :: hc_road(maxsteb)
     real :: hc_roof(maxsteb)
     real :: hc_wall(maxsteb)
     character(len=f_name_length) :: hfilin
     character(len=f_name_length) :: hfilout
     real :: hindu(maxubtp)
     real :: hparm
     real :: hs(maxsndg)
     real :: htraf(maxubtp)
     real :: hybbot
     real :: hybtop
     integer :: i1st_flg
     integer :: iaggr
     character(len=256) :: iapr
     character(len=256) :: iarawi
     character(len=256) :: iasrfce
     integer :: ibnd
     integer :: icFileType
     character(len=256) :: icGradsPrefix
     character(len=256) :: icPrefix
     integer :: iccnlev
     integer :: ichemi
     integer :: ichemi_in
     integer :: iclobber
     integer :: icloud
     integer :: icorflg
     integer :: idate1
     integer :: ideltat
     integer :: idiffk
     integer :: idriz
     integer :: iexev
     integer :: if_adap
     integer :: if_cuinv
     integer :: if_oda
     integer :: if_urban_canopy
     integer :: ifusflg
     character(len=f_name_length) :: ifusfn
     integer :: igraup
     integer :: igridfl
     integer :: ihail
     integer :: ihistdel
     integer :: ihorgrad
     integer :: ihtran
     integer :: ileafcod(maxubtp)
     integer :: ilwrtyp
     integer :: imassflx
     integer :: imonth1
     integer :: initfld
     integer :: initial
     real :: initial_latitude
     real :: initial_longitude
     integer :: inplevs
     integer :: iobswin
     integer :: ioflgisz
     integer :: ioflgvar
     integer :: ioutput
     integer :: ipastin
     integer :: iplaws
     integer :: iplevs(nzpmax)
     character(len=16) :: iplfld(50)
     integer :: ipos
     integer :: ipresslev
     integer :: ipris
     integer :: ipsflg
     integer :: irain
     integer :: irime
     integer :: irtsflg
     integer :: isan_inc
     integer :: isbval(50)
     integer :: isfc_flg
     integer :: isfcl
     integer :: isfcl_ocean
     integer :: isnow
     integer :: isoilflg
     character(len=f_name_length) :: isoilfn
     integer :: isource
     integer :: isstflg
     character(len=f_name_length) :: isstfn
     integer :: iswrtyp
     integer :: iszstage
     integer :: iteb
     integer :: itime1
     integer :: itopsflg
     integer :: itoptflg
     character(len=f_name_length) :: itoptfn
     integer :: itsflg
     integer :: iupa_flg
     integer :: iupdndvi
     integer :: iupdsst
     integer :: iusflg
     integer :: ivegtflg
     character(len=f_name_length) :: ivegtfn
     integer :: ivrstage
     integer :: ixsctn(50)
     integer :: iyear1
     integer :: iz0flg
     integer :: jbnd
     character(len=f_name_length) :: julesin
     integer :: kwrite
     real :: latf
     real :: lati
     integer :: level
     integer :: levth(maxisn)
     character(len=32) :: lite_vars(maxlite)
     integer :: load_bal
     real :: lonf
     real :: loni
     integer :: lonrad
     integer :: lsflg
     character(len=f_name_length) :: mapaotfile
     integer :: maxsfc
     integer :: maxsta
     integer :: mcphys_type
     character(len=3) :: mean_type
     integer :: mech
     character(len=10) :: mechanism
     character(len=f_name_length) :: meteogramDir
     real :: meteogramFreq
     character(len=f_name_length) :: meteogramMap
     integer :: mkcoltab
     integer :: na_extra2d
     integer :: na_extra3d
     integer :: nacoust
     integer :: naddsc
     integer :: ndviflg
     character(len=f_name_length) :: ndvifn
     character(len=f_name_length) :: ndvifpfx
     integer :: nestz1
     integer :: nestz2
     integer :: nfeedvar
     integer :: nfpt
     integer :: ngrids
     integer :: nigrids
     integer :: ninest
     integer :: nisn
     integer :: njnest
     integer :: nknest
     integer :: nlite_vars
     integer :: nndtrat
     integer :: nnqparm
     integer :: nnshcu
     integer :: nnstbot
     integer :: nnsttop
     integer :: nnxp
     integer :: nnyp
     integer :: nnzp
     integer :: nofilflg
     character(len=8) :: notid(50)
     integer :: notsta
     integer :: npatch
     integer :: nplt
     integer :: nslcon
     integer :: nstratx
     integer :: nstraty
     integer :: nstratz1(nzpmax)
     integer :: nstratz2(nzpmax)
     integer :: nteb
     integer :: nud_cond
     character(len=f_name_length) :: nud_hfile
     integer :: nud_type
     integer :: nudlat
     integer :: nurbtype
     integer :: nvegpat
     integer :: nvgcon
     integer :: nvp
     integer :: nxtnest
     integer :: nzg
     integer :: nzs
     real :: oda_sfc_tel
     real :: oda_sfc_til
     character(len=128) :: oda_sfcprefix
     real :: oda_upa_tel
     real :: oda_upa_til
     character(len=128) :: oda_upaprefix
     integer :: order_h
     integer :: order_v
     character(len=f_name_length) :: pastfn
     real :: pctlcon
     integer :: pd_or_mnt_constraint
     real :: pleindu(maxubtp)
     real :: pletraf(maxubtp)
     integer :: plumerise
     real :: polelat
     real :: polelon
     real :: pparm
     real :: prfrq
     character(len=10) :: proj
     integer :: prtcputime
     real :: ps(maxsndg)
     character(len=f_name_length) :: raddatfn
     real :: radfrq
     real :: radtun
     real :: ramp
     integer :: recycle_tracers
     real :: respon(maxagrds)
     real :: roda_hgt(maxodagrids)
     real :: roda_sfc0(maxodagrids)
     real :: roda_sfce(maxodagrids)
     real :: roda_upa0(maxodagrids)
     real :: roda_upae(maxodagrids)
     real :: roda_zfact(maxodagrids)
     real :: rparm
     real :: rts(maxsndg)
     character(len=16) :: runtype
     real :: rushh1
     real :: rushh2
     real :: scale_factor(5)
     real :: seatmp
     character(len=f_name_length) :: sfcfiles
     real :: sfcinf
     real :: shcufrq
     real :: sigzwt
     real :: site_lat
     real :: site_lon
     real :: slmstr(nzgmax)
     real :: slz(nzgmax)
     character(len=1) :: soil_moist
     character(len=1) :: soil_moist_fail
     real :: sparm
     character(len=20) :: split_method
     character(len=256) :: srcmapfn
     character(len=f_name_length) :: sstfpfx
     real :: stasep
     real :: stgoff(nzgmax)
     real :: swvlnth(maxagrds)
     real :: t_nudge_rc
     real :: tc_road(maxsteb)
     real :: tc_roof(maxsteb)
     real :: tc_wall(maxsteb)
     real :: tcond_beg
     real :: tcond_end
     real :: tcu_beg
     real :: tcu_end
     integer :: teb_spm
     character(len=32) :: temperature_varname
     real :: timeWindowIAU
     character(len=1) :: timeunit
     real :: timmax
     real :: timstr
     real :: tminbld
     real :: tnudcent
     real :: tnudcu
     real :: tnudlat
     real :: tnudoda
     real :: tnudtop
     real :: todabeg
     real :: todaend
     character(len=f_name_length) :: topfiles
     real :: topsigz
     real :: toptenh
     real :: toptwvl
     real :: ts(maxsndg)
     real :: ulimit(5)
     character(len=32) :: ur_varname
     real :: us(maxsndg)
     character(len=f_name_length) :: usdata_in
     character(len=f_name_length) :: usmodel_in
     character(len=f_name_length) :: varfpfx
     character(len=256) :: varpfx
     integer :: volcanoes
     character(len=f_name_length) :: vp(200)
     real :: vs(maxsndg)
     integer :: vveldamp
     real :: vwait1
     real :: vwaittot
     real :: wcldbs
     character(len=3) :: weekdayin
     character(len=f_name_length) :: wfFile
     character(len=32) :: wind_u_varname
     character(len=32) :: wind_v_varname
     integer :: windfarm
     real :: wt_cu_grid(maxcugrids)
     real :: wt_nudge_grid
     real :: wt_nudge_pi
     real :: wt_nudge_rt
     real :: wt_nudge_th
     real :: wt_nudge_uv
     real :: wt_nudgec_grid
     real :: wt_oda_grid(maxodagrids)
     real :: wt_oda_pi
     real :: wt_oda_rt
     real :: wt_oda_th
     real :: wt_oda_uv
     real :: wvlnth(maxagrds)
     real :: xkhkm
     character(len=20) :: xlite
     character(len=20) :: ylite
     real :: z0_town(maxubtp)
     real :: z0fact
     real :: z0max
     integer :: z_max_level
     real :: zkhkm
     integer :: zlevmax
     character(len=20) :: zlite
     real :: znudtop
     real :: zrough
     real :: zz(nzpmax)
  end type SingleGridNamelist


contains



  function CreateSingleGridNamelist(oneNamelistFile, gridId) result(res)
    type(NamelistFile), pointer, intent(in) :: oneNamelistFile
    integer :: gridId
    type(SingleGridNamelist), pointer :: res

    integer :: ierr
    character(len=8) :: str(10)
    character(len=*), parameter :: h="**(CreateSingleGridNamelist)**"

    if (.not. associated(oneNamelistFile)) then
       call fatal_error(h//" oneNamelistFile not associated")
    end if

    allocate(res, stat=ierr)
    if (ierr /= 0) then
       write(str(1),"(i8)") ierr
       call fatal_error(h//" allocate res fails with stat="//&
            trim(adjustl(str(1))))
    end if

    res%advmnt = oneNamelistFile%advmnt
    res%aer_assim = oneNamelistFile%aer_assim
    res%aer_timestep = oneNamelistFile%aer_timestep
    res%aerosol = oneNamelistFile%aerosol
    res%afilout = oneNamelistFile%afilout
    res%akmin = oneNamelistFile%akmin(gridId)
    res%albedo = oneNamelistFile%albedo
    res%anl2gra = oneNamelistFile%anl2gra
    res%aparm = oneNamelistFile%aparm
    res%applyDigitalFilter = oneNamelistFile%applyDigitalFilter
    res%applyIAU = oneNamelistFile%applyIAU
    res%applyMeteogram = oneNamelistFile%applyMeteogram
    res%aroad(:) = oneNamelistFile%aroad(:)
    res%aroof(:) = oneNamelistFile%aroof(:)
    res%ascii_data = oneNamelistFile%ascii_data
    res%avgtim = oneNamelistFile%avgtim
    res%awall(:) = oneNamelistFile%awall(:)
    res%bld(:) = oneNamelistFile%bld(:)
    res%bld_height(:) = oneNamelistFile%bld_height(:)
    res%bld_hl_ratio(:) = oneNamelistFile%bld_hl_ratio(:)
    res%catt = oneNamelistFile%catt
    res%ccGradsWrite = oneNamelistFile%ccGradsWrite
    res%ccatt = oneNamelistFile%ccatt
    res%centlat = oneNamelistFile%centlat(gridId)
    res%centlon = oneNamelistFile%centlon(gridId)
    res%chem_assim = oneNamelistFile%chem_assim
    res%chem_timestep = oneNamelistFile%chem_timestep
    res%chemdata_in = oneNamelistFile%chemdata_in
    res%chemistry = oneNamelistFile%chemistry
    res%chemistry_aq = oneNamelistFile%chemistry_aq
    res%closure_type = oneNamelistFile%closure_type
    res%cnparm = oneNamelistFile%cnparm
    res%coltabfn = oneNamelistFile%coltabfn
    res%cond_hfile = oneNamelistFile%cond_hfile
    res%confrq = oneNamelistFile%confrq
    res%cparm = oneNamelistFile%cparm
    res%cphas = oneNamelistFile%cphas
    res%csvFile = oneNamelistFile%csvFile
    res%csx = oneNamelistFile%csx(gridId)
    res%csz = oneNamelistFile%csz(gridId)
    res%cu_prefix = oneNamelistFile%cu_prefix
    res%cu_tel = oneNamelistFile%cu_tel
    res%cu_til = oneNamelistFile%cu_til
    res%d_road(:) = oneNamelistFile%d_road(:)
    res%d_roof(:) = oneNamelistFile%d_roof(:)
    res%d_wall(:) = oneNamelistFile%d_wall(:)
    res%damModule = oneNamelistFile%damModule
    res%damOutPrefix = oneNamelistFile%damOutPrefix
    res%daylight = oneNamelistFile%daylight
    res%def_proc_src = oneNamelistFile%def_proc_src
    res%define_proc = oneNamelistFile%define_proc
    res%deltax = oneNamelistFile%deltax
    res%deltay = oneNamelistFile%deltay
    res%deltaz = oneNamelistFile%deltaz
    res%digitalFilterTimeWindow = oneNamelistFile%digitalFilterTimeWindow
    res%distim = oneNamelistFile%distim
    res%diur_cycle(:) = oneNamelistFile%diur_cycle(:)
    res%dlimit(:) = oneNamelistFile%dlimit(:)
    res%domain_fname = oneNamelistFile%domain_fname
    res%dparm = oneNamelistFile%dparm
    res%drtcon = oneNamelistFile%drtcon
    res%dthcon = oneNamelistFile%dthcon
    res%dtlong = oneNamelistFile%dtlong
    res%dyncore_flag = oneNamelistFile%dyncore_flag
    res%dzmax = oneNamelistFile%dzmax
    res%dzrat = oneNamelistFile%dzrat
    res%efsat = oneNamelistFile%efsat
    res%efsun = oneNamelistFile%efsun
    res%eindco = oneNamelistFile%eindco
    res%eindno = oneNamelistFile%eindno
    res%eindno2 = oneNamelistFile%eindno2
    res%eindpm = oneNamelistFile%eindpm
    res%eindso2 = oneNamelistFile%eindso2
    res%eindvoc = oneNamelistFile%eindvoc
    res%epsil = oneNamelistFile%epsil
    res%eroad(:) = oneNamelistFile%eroad(:)
    res%eroof(:) = oneNamelistFile%eroof(:)
    res%evaluate = oneNamelistFile%evaluate
    res%evaluatePrefix = oneNamelistFile%evaluatePrefix
    res%eveico = oneNamelistFile%eveico
    res%eveino = oneNamelistFile%eveino
    res%eveino2 = oneNamelistFile%eveino2
    res%eveipm = oneNamelistFile%eveipm
    res%eveiso2 = oneNamelistFile%eveiso2
    res%eveivoc = oneNamelistFile%eveivoc
    res%ewall(:) = oneNamelistFile%ewall(:)
    res%expnme = oneNamelistFile%expnme
    res%fileName = oneNamelistFile%fileName
    res%fileNameIAU = oneNamelistFile%fileNameIAU
    res%final_latitude = oneNamelistFile%final_latitude
    res%final_longitude = oneNamelistFile%final_longitude
    res%firemapfn = oneNamelistFile%firemapfn
    res%fixLevels = oneNamelistFile%fixLevels
    res%frqPrecip = oneNamelistFile%frqPrecip
    res%frqanl = oneNamelistFile%frqanl
    res%frqboth = oneNamelistFile%frqboth
    res%frqhis = oneNamelistFile%frqhis
    res%frqlite = oneNamelistFile%frqlite
    res%frqmean = oneNamelistFile%frqmean
    res%frqoda = oneNamelistFile%frqoda
    res%frqprt = oneNamelistFile%frqprt
    res%fusfiles = oneNamelistFile%fusfiles
    res%g3d_smoothh = oneNamelistFile%g3d_smoothh
    res%g3d_smoothv = oneNamelistFile%g3d_smoothv
    res%g3d_spread = oneNamelistFile%g3d_spread
    res%geo_varname = oneNamelistFile%geo_varname
    res%ghostzonelength = oneNamelistFile%ghostzonelength
    res%gnparm = oneNamelistFile%gnparm
    res%gnu(:) = oneNamelistFile%gnu(:)
    res%gobrad = oneNamelistFile%gobrad
    res%gobsep = oneNamelistFile%gobsep
    res%gparm = oneNamelistFile%gparm
    res%gprefix = oneNamelistFile%gprefix
    res%gridu = oneNamelistFile%gridu(gridId)
    res%gridv = oneNamelistFile%gridv(gridId)
    res%gridwt(:) = oneNamelistFile%gridwt(:)
    res%guess1st = oneNamelistFile%guess1st
    res%hc_road(:) = oneNamelistFile%hc_road(:)
    res%hc_roof(:) = oneNamelistFile%hc_roof(:)
    res%hc_wall(:) = oneNamelistFile%hc_wall(:)
    res%hfilin = oneNamelistFile%hfilin
    res%hfilout = oneNamelistFile%hfilout
    res%hindu(:) = oneNamelistFile%hindu(:)
    res%hparm = oneNamelistFile%hparm
    res%hs(:) = oneNamelistFile%hs(:)
    res%htraf(:) = oneNamelistFile%htraf(:)
    res%hybbot = oneNamelistFile%hybbot
    res%hybtop = oneNamelistFile%hybtop
    res%i1st_flg = oneNamelistFile%i1st_flg
    res%iaggr = oneNamelistFile%iaggr
    res%iapr = oneNamelistFile%iapr
    res%iarawi = oneNamelistFile%iarawi
    res%iasrfce = oneNamelistFile%iasrfce
    res%ibnd = oneNamelistFile%ibnd
    res%icFileType = oneNamelistFile%icFileType
    res%icGradsPrefix = oneNamelistFile%icGradsPrefix
    res%icPrefix = oneNamelistFile%icPrefix
    res%iccnlev = oneNamelistFile%iccnlev
    res%ichemi = oneNamelistFile%ichemi
    res%ichemi_in = oneNamelistFile%ichemi_in
    res%iclobber = oneNamelistFile%iclobber
    res%icloud = oneNamelistFile%icloud
    res%icorflg = oneNamelistFile%icorflg
    res%idate1 = oneNamelistFile%idate1
    res%ideltat = oneNamelistFile%ideltat
    res%idiffk = oneNamelistFile%idiffk(gridId)
    res%idriz = oneNamelistFile%idriz
    res%iexev = oneNamelistFile%iexev
    res%if_adap = oneNamelistFile%if_adap
    res%if_cuinv = oneNamelistFile%if_cuinv
    res%if_oda = oneNamelistFile%if_oda
    res%if_urban_canopy = oneNamelistFile%if_urban_canopy
    res%ifusflg = oneNamelistFile%ifusflg(gridId)
    res%ifusfn = oneNamelistFile%ifusfn(gridId)
    res%igraup = oneNamelistFile%igraup
    res%igridfl = oneNamelistFile%igridfl
    res%ihail = oneNamelistFile%ihail
    res%ihistdel = oneNamelistFile%ihistdel
    res%ihorgrad = oneNamelistFile%ihorgrad
    res%ihtran = oneNamelistFile%ihtran
    res%ileafcod(:) = oneNamelistFile%ileafcod(:)
    res%ilwrtyp = oneNamelistFile%ilwrtyp
    res%imassflx = oneNamelistFile%imassflx
    res%imonth1 = oneNamelistFile%imonth1
    res%initfld = oneNamelistFile%initfld
    res%initial = oneNamelistFile%initial
    res%initial_latitude = oneNamelistFile%initial_latitude
    res%initial_longitude = oneNamelistFile%initial_longitude
    res%inplevs = oneNamelistFile%inplevs
    res%iobswin = oneNamelistFile%iobswin
    res%ioflgisz = oneNamelistFile%ioflgisz
    res%ioflgvar = oneNamelistFile%ioflgvar
    res%ioutput = oneNamelistFile%ioutput
    res%ipastin = oneNamelistFile%ipastin
    res%iplaws = oneNamelistFile%iplaws
    res%iplevs(:) = oneNamelistFile%iplevs(:)
    res%iplfld(:) = oneNamelistFile%iplfld(:)
    res%ipos = oneNamelistFile%ipos
    res%ipresslev = oneNamelistFile%ipresslev
    res%ipris = oneNamelistFile%ipris
    res%ipsflg = oneNamelistFile%ipsflg
    res%irain = oneNamelistFile%irain
    res%irime = oneNamelistFile%irime
    res%irtsflg = oneNamelistFile%irtsflg
    res%isan_inc = oneNamelistFile%isan_inc
    res%isbval(:) = oneNamelistFile%isbval(:)
    res%isfc_flg = oneNamelistFile%isfc_flg
    res%isfcl = oneNamelistFile%isfcl
    res%isfcl_ocean = oneNamelistFile%isfcl_ocean
    res%isnow = oneNamelistFile%isnow
    res%isoilflg = oneNamelistFile%isoilflg(gridId)
    res%isoilfn = oneNamelistFile%isoilfn(gridId)
    res%isource = oneNamelistFile%isource
    res%isstflg = oneNamelistFile%isstflg(gridId)
    res%isstfn = oneNamelistFile%isstfn(gridId)
    res%iswrtyp = oneNamelistFile%iswrtyp
    res%iszstage = oneNamelistFile%iszstage
    res%iteb = oneNamelistFile%iteb
    res%itime1 = oneNamelistFile%itime1
    res%itopsflg = oneNamelistFile%itopsflg(gridId)
    res%itoptflg = oneNamelistFile%itoptflg(gridId)
    res%itoptfn = oneNamelistFile%itoptfn(gridId)
    res%itsflg = oneNamelistFile%itsflg
    res%iupa_flg = oneNamelistFile%iupa_flg
    res%iupdndvi = oneNamelistFile%iupdndvi
    res%iupdsst = oneNamelistFile%iupdsst
    res%iusflg = oneNamelistFile%iusflg
    res%ivegtflg = oneNamelistFile%ivegtflg(gridId)
    res%ivegtfn = oneNamelistFile%ivegtfn(gridId)
    res%ivrstage = oneNamelistFile%ivrstage
    res%ixsctn(:) = oneNamelistFile%ixsctn(:)
    res%iyear1 = oneNamelistFile%iyear1
    res%iz0flg = oneNamelistFile%iz0flg(gridId)
    res%jbnd = oneNamelistFile%jbnd
    res%julesin = oneNamelistFile%julesin
    res%kwrite = oneNamelistFile%kwrite
    res%latf = oneNamelistFile%latf(gridId)
    res%lati = oneNamelistFile%lati(gridId)
    res%level = oneNamelistFile%level
    res%levth(:) = oneNamelistFile%levth(:)
    res%lite_vars(:) = oneNamelistFile%lite_vars(:)
    res%load_bal = oneNamelistFile%load_bal
    res%lonf = oneNamelistFile%lonf(gridId)
    res%loni = oneNamelistFile%loni(gridId)
    res%lonrad = oneNamelistFile%lonrad
    res%lsflg = oneNamelistFile%lsflg
    res%mapaotfile = oneNamelistFile%mapaotfile
    res%maxsfc = oneNamelistFile%maxsfc
    res%maxsta = oneNamelistFile%maxsta
    res%mcphys_type = oneNamelistFile%mcphys_type
    res%mean_type = oneNamelistFile%mean_type
    res%mech = oneNamelistFile%mech
    res%mechanism = oneNamelistFile%mechanism
    res%meteogramDir = oneNamelistFile%meteogramDir
    res%meteogramFreq = oneNamelistFile%meteogramFreq
    res%meteogramMap = oneNamelistFile%meteogramMap
    res%mkcoltab = oneNamelistFile%mkcoltab
    res%na_extra2d = oneNamelistFile%na_extra2d
    res%na_extra3d = oneNamelistFile%na_extra3d
    res%nacoust = oneNamelistFile%nacoust
    res%naddsc = oneNamelistFile%naddsc
    res%ndviflg = oneNamelistFile%ndviflg(gridId)
    res%ndvifn = oneNamelistFile%ndvifn(gridId)
    res%ndvifpfx = oneNamelistFile%ndvifpfx
    res%nestz1 = oneNamelistFile%nestz1
    res%nestz2 = oneNamelistFile%nestz2
    res%nfeedvar = oneNamelistFile%nfeedvar
    res%nfpt = oneNamelistFile%nfpt
    res%ngrids = oneNamelistFile%ngrids
    res%nigrids = oneNamelistFile%nigrids
    res%ninest = oneNamelistFile%ninest(gridId)
    res%nisn = oneNamelistFile%nisn
    res%njnest = oneNamelistFile%njnest(gridId)
    res%nknest = oneNamelistFile%nknest(gridId)
    res%nlite_vars = oneNamelistFile%nlite_vars
    res%nndtrat = oneNamelistFile%nndtrat(gridId)
    res%nnqparm = oneNamelistFile%nnqparm(gridId)
    res%nnshcu = oneNamelistFile%nnshcu(gridId)
    res%nnstbot = oneNamelistFile%nnstbot(gridId)
    res%nnsttop = oneNamelistFile%nnsttop(gridId)
    res%nnxp = oneNamelistFile%nnxp(gridId)
    res%nnyp = oneNamelistFile%nnyp(gridId)
    res%nnzp = oneNamelistFile%nnzp(gridId)
    res%nofilflg = oneNamelistFile%nofilflg(gridId)
    res%notid(:) = oneNamelistFile%notid(:)
    res%notsta = oneNamelistFile%notsta
    res%npatch = oneNamelistFile%npatch
    res%nplt = oneNamelistFile%nplt
    res%nslcon = oneNamelistFile%nslcon
    res%nstratx = oneNamelistFile%nstratx(gridId)
    res%nstraty = oneNamelistFile%nstraty(gridId)
    res%nstratz1(:) = oneNamelistFile%nstratz1(:)
    res%nstratz2(:) = oneNamelistFile%nstratz2(:)
    res%nteb = oneNamelistFile%nteb
    res%nud_cond = oneNamelistFile%nud_cond
    res%nud_hfile = oneNamelistFile%nud_hfile
    res%nud_type = oneNamelistFile%nud_type
    res%nudlat = oneNamelistFile%nudlat
    res%nurbtype = oneNamelistFile%nurbtype
    res%nvegpat = oneNamelistFile%nvegpat
    res%nvgcon = oneNamelistFile%nvgcon
    res%nvp = oneNamelistFile%nvp
    res%nxtnest = oneNamelistFile%nxtnest(gridId)
    res%nzg = oneNamelistFile%nzg
    res%nzs = oneNamelistFile%nzs
    res%oda_sfc_tel = oneNamelistFile%oda_sfc_tel
    res%oda_sfc_til = oneNamelistFile%oda_sfc_til
    res%oda_sfcprefix = oneNamelistFile%oda_sfcprefix
    res%oda_upa_tel = oneNamelistFile%oda_upa_tel
    res%oda_upa_til = oneNamelistFile%oda_upa_til
    res%oda_upaprefix = oneNamelistFile%oda_upaprefix
    res%order_h = oneNamelistFile%order_h
    res%order_v = oneNamelistFile%order_v
    res%pastfn = oneNamelistFile%pastfn
    res%pctlcon = oneNamelistFile%pctlcon
    res%pd_or_mnt_constraint = oneNamelistFile%pd_or_mnt_constraint
    res%pleindu(:) = oneNamelistFile%pleindu(:)
    res%pletraf(:) = oneNamelistFile%pletraf(:)
    res%plumerise = oneNamelistFile%plumerise
    res%polelat = oneNamelistFile%polelat
    res%polelon = oneNamelistFile%polelon
    res%pparm = oneNamelistFile%pparm
    res%prfrq = oneNamelistFile%prfrq
    res%proj = oneNamelistFile%proj
    res%prtcputime = oneNamelistFile%prtcputime
    res%ps(:) = oneNamelistFile%ps(:)
    res%raddatfn = oneNamelistFile%raddatfn
    res%radfrq = oneNamelistFile%radfrq
    res%radtun = oneNamelistFile%radtun
    res%ramp = oneNamelistFile%ramp
    res%recycle_tracers = oneNamelistFile%recycle_tracers
    res%respon(:) = oneNamelistFile%respon(:)
    res%roda_hgt(:) = oneNamelistFile%roda_hgt(:)
    res%roda_sfc0(:) = oneNamelistFile%roda_sfc0(:)
    res%roda_sfce(:) = oneNamelistFile%roda_sfce(:)
    res%roda_upa0(:) = oneNamelistFile%roda_upa0(:)
    res%roda_upae(:) = oneNamelistFile%roda_upae(:)
    res%roda_zfact(:) = oneNamelistFile%roda_zfact(:)
    res%rparm = oneNamelistFile%rparm
    res%rts(:) = oneNamelistFile%rts(:)
    res%runtype = oneNamelistFile%runtype
    res%rushh1 = oneNamelistFile%rushh1
    res%rushh2 = oneNamelistFile%rushh2
    res%scale_factor(:) = oneNamelistFile%scale_factor(:)
    res%seatmp = oneNamelistFile%seatmp
    res%sfcfiles = oneNamelistFile%sfcfiles
    res%sfcinf = oneNamelistFile%sfcinf
    res%shcufrq = oneNamelistFile%shcufrq
    res%sigzwt = oneNamelistFile%sigzwt
    res%site_lat = oneNamelistFile%site_lat
    res%site_lon = oneNamelistFile%site_lon
    res%slmstr(:) = oneNamelistFile%slmstr(:)
    res%slz(:) = oneNamelistFile%slz(:)
    res%soil_moist = oneNamelistFile%soil_moist
    res%soil_moist_fail = oneNamelistFile%soil_moist_fail
    res%sparm = oneNamelistFile%sparm
    res%split_method = oneNamelistFile%split_method
    res%srcmapfn = oneNamelistFile%srcmapfn
    res%sstfpfx = oneNamelistFile%sstfpfx
    res%stasep = oneNamelistFile%stasep
    res%stgoff(:) = oneNamelistFile%stgoff(:)
    res%swvlnth(:) = oneNamelistFile%swvlnth(:)
    res%t_nudge_rc = oneNamelistFile%t_nudge_rc
    res%tc_road(:) = oneNamelistFile%tc_road(:)
    res%tc_roof(:) = oneNamelistFile%tc_roof(:)
    res%tc_wall(:) = oneNamelistFile%tc_wall(:)
    res%tcond_beg = oneNamelistFile%tcond_beg
    res%tcond_end = oneNamelistFile%tcond_end
    res%tcu_beg = oneNamelistFile%tcu_beg
    res%tcu_end = oneNamelistFile%tcu_end
    res%teb_spm = oneNamelistFile%teb_spm
    res%temperature_varname = oneNamelistFile%temperature_varname
    res%timeWindowIAU = oneNamelistFile%timeWindowIAU
    res%timeunit = oneNamelistFile%timeunit
    res%timmax = oneNamelistFile%timmax
    res%timstr = oneNamelistFile%timstr
    res%tminbld = oneNamelistFile%tminbld
    res%tnudcent = oneNamelistFile%tnudcent
    res%tnudcu = oneNamelistFile%tnudcu
    res%tnudlat = oneNamelistFile%tnudlat
    res%tnudoda = oneNamelistFile%tnudoda
    res%tnudtop = oneNamelistFile%tnudtop
    res%todabeg = oneNamelistFile%todabeg
    res%todaend = oneNamelistFile%todaend
    res%topfiles = oneNamelistFile%topfiles
    res%topsigz = oneNamelistFile%topsigz
    res%toptenh = oneNamelistFile%toptenh(gridId)
    res%toptwvl = oneNamelistFile%toptwvl(gridId)
    res%ts(:) = oneNamelistFile%ts(:)
    res%ulimit(:) = oneNamelistFile%ulimit(:)
    res%ur_varname = oneNamelistFile%ur_varname
    res%us(:) = oneNamelistFile%us(:)
    res%usdata_in = oneNamelistFile%usdata_in
    res%usmodel_in = oneNamelistFile%usmodel_in
    res%varfpfx = oneNamelistFile%varfpfx
    res%varpfx = oneNamelistFile%varpfx
    res%volcanoes = oneNamelistFile%volcanoes
    res%vp(:) = oneNamelistFile%vp(:)
    res%vs(:) = oneNamelistFile%vs(:)
    res%vveldamp = oneNamelistFile%vveldamp
    res%vwait1 = oneNamelistFile%vwait1
    res%vwaittot = oneNamelistFile%vwaittot
    res%wcldbs = oneNamelistFile%wcldbs
    res%weekdayin = oneNamelistFile%weekdayin
    res%wfFile = oneNamelistFile%wfFile
    res%wind_u_varname = oneNamelistFile%wind_u_varname
    res%wind_v_varname = oneNamelistFile%wind_v_varname
    res%windfarm = oneNamelistFile%windfarm
    res%wt_cu_grid(:) = oneNamelistFile%wt_cu_grid(:)
    res%wt_nudge_grid = oneNamelistFile%wt_nudge_grid(gridId)
    res%wt_nudge_pi = oneNamelistFile%wt_nudge_pi
    res%wt_nudge_rt = oneNamelistFile%wt_nudge_rt
    res%wt_nudge_th = oneNamelistFile%wt_nudge_th
    res%wt_nudge_uv = oneNamelistFile%wt_nudge_uv
    res%wt_nudgec_grid = oneNamelistFile%wt_nudgec_grid(gridId)
    res%wt_oda_grid(:) = oneNamelistFile%wt_oda_grid(:)
    res%wt_oda_pi = oneNamelistFile%wt_oda_pi
    res%wt_oda_rt = oneNamelistFile%wt_oda_rt
    res%wt_oda_th = oneNamelistFile%wt_oda_th
    res%wt_oda_uv = oneNamelistFile%wt_oda_uv
    res%wvlnth(:) = oneNamelistFile%wvlnth(:)
    res%xkhkm = oneNamelistFile%xkhkm(gridId)
    res%xlite = oneNamelistFile%xlite
    res%ylite = oneNamelistFile%ylite
    res%z0_town(:) = oneNamelistFile%z0_town(:)
    res%z0fact = oneNamelistFile%z0fact
    res%z0max = oneNamelistFile%z0max(gridId)
    res%z_max_level = oneNamelistFile%z_max_level
    res%zkhkm = oneNamelistFile%zkhkm(gridId)
    res%zlevmax = oneNamelistFile%zlevmax(gridId)
    res%zlite = oneNamelistFile%zlite
    res%znudtop = oneNamelistFile%znudtop
    res%zrough = oneNamelistFile%zrough
    res%zz(:) = oneNamelistFile%zz(:)
  end function CreateSingleGridNamelist





  subroutine DestroySingleGridNamelist(oneSingleGridNamelist)
    type(SingleGridNamelist), pointer, intent(inout) :: oneSingleGridNamelist

    integer :: ierr
    character(len=8) :: str(10)
    character(len=*), parameter :: h="**(DestroySingleGridNamelist)**"
    
    if (associated(oneSingleGridNamelist)) then
       deallocate(oneSingleGridNamelist, stat=ierr)
       if (ierr /= 0) then
          write(str(1),"(i8)") ierr
          call fatal_error(h//" deallocate oneSingleGridNamelist fails with stat="//&
               trim(adjustl(str(1))))
       end if
    end if
    nullify(oneSingleGridNamelist)
  end subroutine DestroySingleGridNamelist

end module ModSingleGridNamelist
