ObjSrcActionAtDependUtils=[
    ('an_header.o', '$(UTILS_MODS)/an_header.f90', 'None'), 
    ('ModDateUtils.o', '$(UTILS_MODS)/ModDateUtils.f90', 'None'),
    ('charutils.o', '$(UTILS_LIB)/charutils.f90', 'None'),
    ('dateutils.o', '$(UTILS_LIB)/dateutils.f90', 'None'),
    ('error_mess.o','$(UTILS_LIB)/error_mess.f90', 'None'),
    ('ModGetVar.o',    '$(UTILS_LIB)/ModGetVar.f90', 'None'),
    ('interp_lib.o','$(UTILS_LIB)/interp_lib.f90', 'None'),
    ('hdf5_utils.o', '$(UTILS_LIB)/hdf5_utils.F90', 'None'),
    ('htint-opt.o', '$(UTILS_LIB)/htint-opt.f90', 'None'),
    ('map_proj.o',  '$(UTILS_LIB)/map_proj.f90', 'None'),
    ('utilsMod.o','$(UTILS_LIB)/utilsMod.f90', 'None'),
    ('ModMemory.o',  '$(UTILS_LIB)/ModMemory.f90', 'None'),
    ('numutils.o',  '$(UTILS_LIB)/numutils.f90', 'None'),
    ('polarst.o',   '$(UTILS_LIB)/polarst.f90', 'None'),
    ('therm_lib.o', '$(UTILS_LIB)/therm_lib.f90', 'None'),
    ('utils_f.o',   '$(UTILS_LIB)/utils_f.f90', 'None'),
    ('vformat.o',   '$(UTILS_LIB)/vformat.f90', 'None'),
    ('filelist.o',  '$(UTILS_LIB)/filelist.F90', 'None'),
    ('rsys.o',      '$(UTILS_LIB)/rsys.F90', 'None'),
    ('parlibf.o','$(UTILS_LIB)/parlibf.F90', 'None'),
    ('satPolyColision.o','$(UTILS_LIB)/satPolyColision.f90', 'None'),
    ('dump.o','$(UTILS_DUMP)/dump.F90', 'None'),
    ('module_gate.o','$(UTILS_MDTOOLS)/module_gate.f90', 'None'),
    ('gammaFunction.o',  '$(UTILS_LIB)/gammaFunction.f90', 'None'),
    ('generic.o',  '$(UTILS_LIB)/generic.f90', 'None'),
]
